services:
  tf:
    build: .
    command: >
      bash -c "cd ../poetry 
      && python3 -m poetry config virtualenvs.create false
      && python3 -m poetry install --no-interaction --no-ansi
      && source /etc/bash.bashrc 
      && jupyter lab --notebook-dir=/tf/ --ip 0.0.0.0 --no-browser --allow-root"
    ports:
      - "8888:8888"
    volumes:
      - "./Notebooks/:/tf"
      - "./poetry:/poetry"
    runtime: "nvidia"